### ISSUE TITLE
Unknown Error in MFA Preventing Dataset Creation

### ISSUE THREAD

**Issue by mago3421** [castorini/howl#113]
Hi,

I am trying to generate a custom dataset for the wake word "scissors" according to the dataset generation instructions. However, I am encountering this error which complains about a missing file. The error concerns MFA.

`/home/mago3421/howl/montreal-forced-aligner$ ./bin/mfa_align --num_jobs 12 ../datasets/scissors/positive/audio librispeech-lexicon.txt pretrained_models/english.zip ../datasets/scissors/positive/alignment
align.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 12.0
/home/mago3421/howl/montreal-forced-aligner/lib/aligner/models.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Creating dictionary information...
Setting up training data...
There were words not found in the dictionary. Would you like to abort to fix them? (Y/N)N
Calculating MFCCs...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 94, in align_corpus
  File "aligner/aligner/pretrained.py", line 74, in __init__
  File "aligner/aligner/pretrained.py", line 122, in setup
  File "aligner/aligner/base.py", line 89, in setup
  File "aligner/corpus.py", line 979, in initialize_corpus
  File "aligner/corpus.py", line 852, in create_mfccs
  File "aligner/corpus.py", line 863, in _combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/home/mgonza927/Documents/MFA/audio/train/mfcc/raw_mfcc.0.scp'
[1929911] Failed to execute script align`

Thanks in advance.

**Comment by ljj7975** [comment]
Take a look at the message added in this [readme](https://github.com/castorini/howl/tree/master/howl/dataset) recently for step 5.

You will need to take a look at [this issue](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/149#issuecomment-621165857)
