### ISSUE TITLE
pip install howl does not work

### ISSUE THREAD

**Issue by ayeganov** [castorini/howl#46]
As the title says - running `pip install howl` ends up with the following output:

```
ERROR: Could not find a version that satisfies the requirement howl
ERROR: No matching distribution found for howl
```

**Comment by ljj7975** [comment]
it's still WIP.
@edwinzhng you can possibly follow up with this issue

**Comment by edwinzhng** [comment]
Hey @ayeganov, I just published the initial version of the package to https://pypi.org/project/howl/. Give it a try and let me know if it works now

**Comment by ayeganov** [comment]
Hi @edwinzhng, thanks for the quick follow up. I think you may need to specify what exact version of python you are using, because even though I was able to successfully install `howl`, running the test program fails:

```
Traceback (most recent call last):
  File "/tmp/test.py", line 1, in <module>
    from howl.client import HowlClient
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/howl/client/__init__.py", line 1, in <module>
    from .howl_client import *
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/howl/client/howl_client.py", line 9, in <module>
    from howl.context import InferenceContext
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/howl/context.py", line 5, in <module>
    from howl.data.dataset import WordFrameLabeler, PhoneticFrameLabeler, PronunciationDictionary, PhonePhrase
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/howl/data/dataset/__init__.py", line 2, in <module>
    from .dataset import *
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/howl/data/dataset/dataset.py", line 13, in <module>
    from howl.utils.audio import silent_load
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/howl/utils/audio.py", line 3, in <module>
    import librosa
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/librosa/core/__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/librosa/core/time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/librosa/util/utils.py", line 10, in <module>
    import numba
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/numba/__init__.py", line 25, in <module>
    from .decorators import autojit, cfunc, generated_jit, jit, njit, stencil
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/numba/decorators.py", line 12, in <module>
    from .targets import registry
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/numba/targets/registry.py", line 5, in <module>
    from . import cpu
  File "/home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/numba/targets/cpu.py", line 9, in <module>
    from numba import _dynfunc, config
ImportError: /home/ainindza/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/numba/_dynfunc.cpython-38-x86_64-linux-gnu.so: undefined symbol: _PyObject_GC_UNTRACK
```

When I was trying to get `howl` to work before your response I had to change the numba version to `0.45.0` when using python 3.8.3 to get things to cooperate.

**Comment by ayeganov** [comment]
Also, when I got `howl` to install and got past the error above - I ran into a problem with the naming: the pre-downloaded model contains the settings file named `setting.json`, while the `workspace.py:65` expects it to be called `settings.json` - extra `s` at the end.

**Comment by edwinzhng** [comment]
Try clearing your cache under `~/.cache/howl`, I made some changes to the naming

**Comment by edwinzhng** [comment]
Also thanks for letting me know about the numba issue, I just updated all the requirements so things should work with Python 3.8 now. Maybe try installing the latest release again and let me know if it works

**Comment by ayeganov** [comment]
YES! `pip install howl` worked and running the example app also worked.

**Comment by ljj7975** [comment]
@ayeganov can we close this issue?
